### ISSUE TITLE
Поддержка sidechain сети

### ISSUE THREAD

**Issue by vol4tim** [airalab/dapp-robonomics.network#1]
Нужно показать какая сейчас сеть включена, mainnet или sidechain.
Какие то элементы будут не доступны в сайдчейне, например перегонного куба не будет, токенов aira и aira id

**Comment by positivecrash** [comment]
Сделала возможность показа названия сети. Также на примере элементов в верхнем меню показала как можно делать эл-ты интерфейса не доступными + подсказки. См. репозиторий https://github.com/airalab/html-dapp.robonomics.network
