### ISSUE TITLE
Broadcast mechanism of demand for dapp

### ISSUE THREAD

**Issue by ensrationis** [airalab/dapp-robonomics.network#4]
When a user signs message via dapp we can start broadcast signal to Robonomics network. I think if we will resend the message every 5 seconds in the first 15 sec and after if dapp not received offer or signal from the provider about creating smart contract then we should start to broadcast message every 30 sec before user will close the dapp window.

**Comment by vol4tim** [comment]
https://github.com/airalab/dapp-robonomics.network/commit/1b25fd1fa949ff98b9d202fea9048f1e30e0ee21
