### ISSUE TITLE
Disconnected... remove of fix connection status of user dapp

### ISSUE THREAD

**Issue by ensrationis** [airalab/dapp-robonomics.network#8]
![Screenshot from 2020-05-20 11-52-57](https://user-images.githubusercontent.com/14291169/82420301-98569280-9a90-11ea-9857-a948936e2933.png)
Connection status on right top corner works strange and unpredictable. For example i see data from telemetry but status is disconnected. Pls fix it or remove this label from UI before we will find more suitable option to show connection status of user dapp.

**Comment by vol4tim** [comment]
Fixed
